apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kube-review-
commonAnnotations:
    app.kubernetes.io/version: "0.3"
commonLabels:
  app.kubernetes.io/instance: re-kube-review
  app.kubernetes.io/name: kube-review
resources:
  - serviceaccount.yml
  - service.yml
  - ingress.yml
  - test-connection.yml
  - deployment.yml

secretGenerator:
- name: secret
  envs:
  - env.txt
  type: Opaque
  options:
    disableNameSuffixHash: true

patches:
  - patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 8880
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8880
    target:
      kind: Service
  - patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: re-website-proxy-xxx.shared-stg.fih.io
      - op: replace
        path: /spec/rules/0/host
        value: re-website-proxy-xxx.shared-stg.fih.io
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/serviceName
        value: kube-review-service-re-website-proxy-xxx
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/servicePort
        value: 8880
    target:
      kind: Ingress
  - path: patches/test-connection.json
    target:
      kind: Pod
      name: test-connection
  - patch: |-
      - op: replace
        path: /spec/template/metadata/annotations/rollme
        value: kjdksl
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 265409992602.dkr.ecr.eu-west-1.amazonaws.com/daedalus-proxy-main:44eddfd
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: re-website-proxy-xxx.shared-stg.fih.io
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8880
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
        value: 8880
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
        value: 8880
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/port
        value: 8880
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: kube-review-serviceaccount
    target:
      kind: Deployment
      name: deployment
