apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kube-review-
commonAnnotations:
    app.kubernetes.io/version: "0.5"
commonLabels:
  app.kubernetes.io/name: kube-review
resources:
  - namespace.yml
  - serviceaccount.yml
  - service.yml
  - ingress.yml
  - deployment.yml

secretGenerator:
- name: secret
  envs:
  - env.txt
  type: Opaque
  options:
    disableNameSuffixHash: true

patches:
  - path: patches/service.patch.json
    target:
      kind: Service
  - path: patches/ingress.patch.json
    target:
      kind: Ingress
  - path: patches/deployment.patch.json
    target:
      kind: Deployment
      name: deployment
  - path: patches/namespace.patch.json
    target:
      kind: Namespace
