version: "1.0"
stages:
  - "run"

steps:
  stop-stale:
    title: "Pruning Envs"
    type: freestyle
    stage: run
    # This has to be the full image uri otherwise it doesn't work
    image: ${{IMAGE_REGISTRY_URL}}/${{IMAGE_NAME}}
    commands:
      - "/prune --cfToken=$CF_TOKEN --k8sKubeconfig=$CF_KUBECONFIG_PATH --k8sContextName=$K8S_CONTEXT_NAME --name=cf-review*"
