version: "1.0"
stages:
  - "run"

steps:
  get_git_token:
    title: Reading GitHub token
    image: codefresh/cli
    commands:
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)

  stop-stale:
    title: "Pruning Envs"
    type: freestyle
    stage: run
    # This has to be the full image uri otherwise it doesn't work
    image: ${{IMAGE_REGISTRY_URL}}/${{IMAGE_NAME}}:${{IMAGE_TAG}}
    commands:
      - "/prune --cfToken=$CF_TOKEN --k8sKubeconfig=$CF_KUBECONFIG_PATH
        --k8sContextName=$K8S_CONTEXT_NAME --ghToken=$GITHUB_TOKEN --ghUserName=$GITHUB_USERNAME"
