{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cf-review-env.fullname" . }}
  labels:
    {{- include "cf-review-env.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cf-review-env.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas | default "1" }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas | default "2" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage | default "90" }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage | default "90" }}
{{- end }}
