apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-cleaner-global
subjects:
- kind: ServiceAccount
  name: {{ include "kube-review-prune.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: namespace-cleaner
  apiGroup: rbac.authorization.k8s.io