apiVersion: v1
kind: Secret
metadata:
  name: aws-route53-secret-access-key-secret
  namespace: cert-manager
data:
  secret-access-key: ${EKS_CERT_MANAGER_ROUTE53_AWS_SECRET_ACCESS_KEY_BASE64}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prd
  namespace: cert-manager
  labels:
    name: letsencrypt-prd
spec:
  acme:
    email: your-email-here@mail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prd
    solvers:
    - selector:
        dnsZones:
          - ${MY_DOMAIN}
      dns01:
        route53:
          region: eu-west-1
          accessKeyID: ${EKS_CERT_MANAGER_ROUTE53_AWS_ACCESS_KEY_ID}
          secretAccessKeySecretRef:
            name: aws-route53-secret-access-key-secret
            key: secret-access-key
