version: "1.0"
stages:
  - clone
  - helm
  - build

steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: FindHotel/cf-review-env
    revision: ${{CF_BRANCH}}
    git: github
    stage: clone

  push:
    stage: helm
    title: Push to the Repository
    type: helm
    working_directory: ./cf-review-env
    arguments:
      action: push
      helm_version: ${{K8S_HELM_VERSION}}
      chart_name: charts/cf-review-env
      chart_repo_url: ${{K8S_CHART_REPOSITORY}}
      skip_cf_stable_helm_repo: true
      kube_context: ${{K8S_CONTEXT_NAME}}

  build:
    title: Building Docker image
    type: build
    image_name: ${{IMAGE_NAME}}
    working_directory: ${{clone}}
    tag: latest
    tags:
      - ${{CF_SHORT_REVISION}}
      - ${{CF_BRANCH_TAG_NORMALIZED}}
      - latest
    dockerfile: Dockerfile
    stage: build
    registry: ${{IMAGE_REGISTRY_NAME}}
    build_arguments:
      - DEFAULT_HELM_REPO_URL=${{K8S_CHART_REPOSITORY}}
