replicaCount: 1
image:
  pullPolicy: Always
serviceAccount:
  create: true
deployment:
  ports:
    name: web
    containerPort: 5000
    protocol: TCP
restartPolicy: Always
terminationGracePeriodSeconds: 40
dnsPolicy: ClusterFirst
progressDeadlineSeconds: 600
revisionHistoryLimit: 10
service:
  type: ClusterIP
  port: 5000
  name: web
  protocol: TCP
  targetPort: 5000
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
resources:
  limits:
    cpu: "1"
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 600Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
livenessProbe:
  httpGet:
    path: "/"
    scheme: "HTTP"
    initialDelaySeconds: 10
    timeoutSeconds: 15
startupProbe:
  httpGet:
    path: "/"
    scheme: "HTTP"
    periodSeconds: 5
    failureThreshold: 100
envFrom:
  secretRef:
    name: "change_me_if_necessary"