serviceAccount:
  create: true
deployment:
  ports:
    name: web
    containerPort: 5000
service:
  name: web
  port: 5000
  targetPort: 5000
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
resources:
  limits:
    cpu: "1"
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 600Mi
autoscaling:
  enabled: true
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
livenessProbe:
  httpGet:
    path: "/"
readinessProbe:
  httpGet:
    path: "/"
startupProbe:
  httpGet:
    path: "/"
envFrom:
  enabled: true
dockerDind:
  enabled: false
customHelmTestURL:
  enabled: false
  args: "/ping/1"
# Example: https://URL/ping/1
