name: ci
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  helm:
    name: Push to the Repository
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Push
        shell: bash
        env:
          HELM_REPO_ACCESS_TOKEN: ${{ secrets.CF_API_KEY }}
          HELM_REPO_AUTH_HEADER: Authorization
        run: |
          helm version --short -c
          helm plugin install https://github.com/chartmuseum/helm-push.git
          helm repo add remote cm://h.cfcr.io/findhotel/lab/
          helm dependency build charts/kube-review || helm dependency update charts/kube-review || echo "dependencies cannot be updated"
          PACKAGE="$(helm package charts/kube-review --version 0.0.1+${{ github.sha }} --destination /tmp | cut -d " " -f 8)"
          helm push $PACKAGE remote
          helm dependency build charts/kube-review-prune || helm dependency update charts/kube-review-prune || echo "dependencies cannot be updated"
          PACKAGE="$(helm package charts/kube-review-prune --version 0.0.1+${{ github.sha }} --destination /tmp | cut -d " " -f 8)"
          helm push $PACKAGE remote

  build:
    name: Building Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:
            - findhotelamsterdam/kube-review:${{ github.sha }},findhotelamsterdam/kube-review:${{ steps.extract_branch.outputs.branch }}
          build-args:
            - ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
            - ECR_REPOSITORY=cf-review-env-prod
            - DEFAULT_HELM_REPO_URL=cm://h.cfcr.io/findhotel/lab/
